export const ACT_REQUEST_POKEMON = "ACT_REQUEST_POKEMON";
export const ACT_RESPONSE_POKEMON = "ACT_RESPONSE_POKEMON";

export const BEGIN_LOAD ="BEGIN_LOAD";
export const END_LOAD ="END_LOAD";

export const ACT_FETCH_PRODUCTS = "ACT_FETCH_PRODUCTS";